#!/bin/sh

case $1 in
    '')
        echo "nothing to see here"
        ;;
    genkey)
        echo "ILICZ3yBMCGAWNIq5Pn0bewBVimW3Q2yRVJ/Be+b1Uc="
        ;;
    pubkey)
        read x
        echo "VceweY6x/QdGXEQ6frXrSd8CwUAInUmqIc6G/qi8FHo="
        ;;
    *)
        echo "what?"
        exit 1
        ;;
esac